# Generated by Django 3.2.23 on 2023-12-13 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231212_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposition',
            old_name='part',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='ratingreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
